swagger: "2.0"
info:
  title: Milkinium API
  description: Oficial API documentation for Milkinium Test Case management system
  version: "1.0.0"
# the domain of the service
host: localhost:5000
# array of all schemes that your API supports
schemes:
  - http
  - https
# will be prefixed to all paths
basePath: /v1
securityDefinitions:
  apikey:
    type: apiKey
    name: Authorization
    in: header
produces:
  - application/json
paths:
  /authenticate:
    post:
      summary: Authentication end point
      description: The endpoint allows you to authenticate in the system
      tags:
        - Auth
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/Auth'
      responses:
        "200":
          description: An auth token

  /users:
    get:
      summary: Get All Users
      description: The endpoint returns all users
      security: 
        - apikey: []
      tags: 
        - User
      responses:
        "200":
          description: An array of users
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
              
  /users/{userId}:
    get:
      summary: Get a user
      description: Get a user by ID
      security:
        - apikey: []
      tags:
        - User
      parameters: 
        - in: path
          name: userId
          schema:
            type: string
          required: true
      responses:
        "200":
          description: A user
          schema:
            $ref: '#/definitions/User'
            
    delete:
      summary: Delete a user
      description: Delete a user by ID
      security:
        - apikey: []
      tags:
        - User
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Success status
          
    put:
      summary: Update a user info
      description: Update a user information
      security: 
        - apikey: []
      tags:
        - User
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
        - in: body
          schema:
            $ref: '#/definitions/User'
      responses:
        "200":
          description: Updated version of the user
          schema:
            $ref: '#/definitions/User'
            
  /projects:
    get:
      summary: Get All Projects
      description: The endpoint returns all projects
      security: 
        - apikey: []
      tags: 
        - Project
      responses:
        "200":
          description: An array of projects
          schema:
            type: array
            items:
              $ref: '#/definitions/Project'
              
  /projects/{userId}:
    get:
      summary: Get a Project
      description: Get a project by ID
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
      security: 
        - apikey: []
      tags:
        - Project
      responses:
        "200":
          description: A project
          schema:
            $ref: '#/definitions/Project'
      
            
# Models defenitions  
definitions:

  # User model
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      email: 
        type: "string"
      password:
        type: "string"
      avatar:
        type: "string"
      name:
        $ref: "#/definitions/Name"
      role:
        type: "string"
        description: "The user role"
        enum:
        - "client"
        - "admin"
    xml:
      name: "Order"

  # Name defenition
  Name:
    type: "object"
    properties:
      first: 
        type: "string"
      last: 
        type: "string"
        
  Project:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
      
        
  # Auth data
  Auth:
    type: "object"
    properties:
      email:
        type: "string"
      password:
        type: "string"
