swagger: "2.0"
info:
  title: Milkinium API
  description: Oficial API documentation for Milkinium Test Case management system
  version: "1.0.0"
# the domain of the service
host: localhost:5000
# array of all schemes that your API supports
schemes:
  - http
  - https
# will be prefixed to all paths
basePath: /v1
securityDefinitions:
  apikey:
    type: apiKey
    name: apiKey
    in: header
produces:
  - application/json
paths:
  /authenticate:
    post:
      summary: Authentication end point
      description: The endpoint allows you to authenticate in the system
      parameters:
        - name: email
          in: body
          schema:
            $ref: '#/definitions/User'
      responses:
        "200":
          description: An auth token

  /users:
    get:
      summary: Get All Users
      description: The endpoint returns all users
      security: 
        - apikey: []
      tags: 
        - User
      responses:  
        "200":
          description: An array of users
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      email: 
        type: "string"
      password:
        type: "string"
      avatar:
        type: "string"
      name:
        type: "object"
        $ref: "#/definitions/Name"
      role:
        type: "string"
        description: "The user role"
        enum:
        - "client"
        - "admin"
    xml:
      name: "Order"

  Name:
    type: "string"
    properties:
      first: 
        type: "string"
      last: 
        last: "string"
